### ISSUE TITLE
letter_opener_web/application_controller (LoadError) on production

### ISSUE THREAD

**Issue by itsmechlark** [fgrehm/letter_opener_web#37]
<b>routes.rb</b>

```
begin
      require 'letter_opener_web/engine'
      mount LetterOpenerWeb::Engine, at: '/letter_opener'
    rescue LoadError => e
      # not installed
    end
```

```
group :development, :beta do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'letter_opener_web'
end
```

```
No such file to load -- letter_opener_web/application_controller (LoadError)
  /var/www/apps/cms/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:247:in `require'
  /var/www/apps/cms/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:247:in `block in require'
  /var/www/apps/cms/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:232:in `load_dependency'
  /var/www/apps/cms/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:247:in `require'
  /var/www/apps/cms/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:348:in `require_or_load'
  /var/www/apps/cms/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:307:in `depend_on'
  /var/www/apps/cms/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:225:in `require_dependency'
  /var/www/apps/cms/shared/bundle/ruby/2.1.0/gems/railties-4.1.7/lib/rails/engine.rb:468:in `block (2 levels) in eager_load!'
  /var/www/apps/cms/shared/bundle/ruby/2.1.0/gems/railties-4.1.7/lib/rails/engine.rb:467:in `each'
  /var/www/apps/cms/shared/bundle/ruby/2.1.0/gems/railties-4.1.7/lib/rails/engine.rb:467:in `block in eager_load!'
  /var/www/apps/cms/shared/bundle/ruby/2.1.0/gems/railties-4.1.7/lib/rails/engine.rb:465:in `each'
  /var/www/apps/cms/shared/bundle/ruby/2.1.0/gems/railties-4.1.7/lib/rails/engine.rb:465:in `eager_load!'
  /var/www/apps/cms/shared/bundle/ruby/2.1.0/gems/railties-4.1.7/lib/rails/engine.rb:346:in `eager_load!'
  /var/www/apps/cms/shared/bundle/ruby/2.1.0/gems/railties-4.1.7/lib/rails/application/finisher.rb:58:in `each'
  /var/www/apps/cms/shared/bundle/ruby/2.1.0/gems/railties-4.1.7/lib/rails/application/finisher.rb:58:in `block in <module:Finisher>'
  /var/www/apps/cms/shared/bundle/ruby/2.1.0/gems/railties-4.1.7/lib/rails/initializable.rb:30:in `instance_exec'
  /var/www/apps/cms/shared/bundle/ruby/2.1.0/gems/railties-4.1.7/lib/rails/initializable.rb:30:in `run'
  /var/www/apps/cms/shared/bundle/ruby/2.1.0/gems/railties-4.1.7/lib/rails/initializable.rb:55:in `block in run_initializers'
  /home/webserver/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/tsort.rb:226:in `block in tsort_each'
  /home/webserver/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
  /home/webserver/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/tsort.rb:427:in `each_strongly_connected_component_from'
  /home/webserver/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/tsort.rb:347:in `block in each_strongly_connected_component'
  /home/webserver/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/tsort.rb:345:in `each'
  /home/webserver/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/tsort.rb:345:in `call'
  /home/webserver/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/tsort.rb:345:in `each_strongly_connected_component'
  /home/webserver/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/tsort.rb:224:in `tsort_each'
  /home/webserver/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/tsort.rb:205:in `tsort_each'
  /var/www/apps/cms/shared/bundle/ruby/2.1.0/gems/railties-4.1.7/lib/rails/initializable.rb:54:in `run_initializers'
  /var/www/apps/cms/shared/bundle/ruby/2.1.0/gems/railties-4.1.7/lib/rails/application.rb:300:in `initialize!'
  /var/www/apps/cms/releases/20141117010133/config/environment.rb:7:in `<top (required)>'
  config.ru:3:in `require'
  config.ru:3:in `block in <main>'
  /var/www/apps/cms/shared/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/builder.rb:55:in `instance_eval'
  /var/www/apps/cms/shared/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/builder.rb:55:in `initialize'
  config.ru:1:in `new'
  config.ru:1:in `<main>'
  /home/webserver/.rvm/gems/ruby-2.1.2/gems/passenger-4.0.46/helper-scripts/rack-preloader.rb:112:in `eval'
  /home/webserver/.rvm/gems/ruby-2.1.2/gems/passenger-4.0.46/helper-scripts/rack-preloader.rb:112:in `preload_app'
  /home/webserver/.rvm/gems/ruby-2.1.2/gems/passenger-4.0.46/helper-scripts/rack-preloader.rb:158:in `<module:App>'
  /home/webserver/.rvm/gems/ruby-2.1.2/gems/passenger-4.0.46/helper-scripts/rack-preloader.rb:29:in `<module:PhusionPassenger>'
  /home/webserver/.rvm/gems/ruby-2.1.2/gems/passenger-4.0.46/helper-scripts/rack-preloader.rb:28:in `<main>'
```

rails 4.1.7

**Comment by fgrehm** [comment]
Sorry for the delay but this is very weird. You seem to be running it on a prod-like environment since from the stacktrace you got passenger running. Am I correct? If that is what you really want, you need to move this gem out of the development group on your Gemfile or run the app in an environment that will load the gem (`beta` would do the trick I guess).

Oh, and BTW, there's no need to require the gem on the routes file :-)

**Comment by itsmechlark** [comment]
Sorry for the delayed response. Yes it's running on production, but why is `letter_opener_web` being load at production when it is in group `development` and `beta`?

Thank you

**Comment by fgrehm** [comment]
No idea, do you mind trying to remove the `begin` ... `rescue` block from your `routes.rb` and replace it with:

```ruby
  if Rails.env.development? || Rails.env.beta?
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
  end
```

?

**Comment by pseudomuto** [comment]
This is very old at this point and has no recent activity. I'm going to close it for now. Feel free to open a new issue/PR if this is still a concern.
