### ISSUE TITLE
NoMethodError in LetterOpenerWeb::LettersController#show

### ISSUE THREAD

**Issue by Blue-Dog-Archolite** [fgrehm/letter_opener_web#47]
Got a bit of an issue loading emails:

Rails 3.2.X
Ruby 1.9.X

any suggestions?

Email is view able in `tmp/letter_opener`

http://awesomescreenshot.com/0ef5rbesc0

```

NoMethodError in LetterOpenerWeb::LettersController#show

undefined method `segment_keys' for nil:NilClass

Rails.root: /home/thief/dev/flight
Application Trace | Framework Trace | Full Trace

actionpack (3.2.22) lib/action_dispatch/routing/mapper.rb:443:in `block (2 levels) in define_generate_prefix'
actionpack (3.2.22) lib/action_dispatch/routing/route_set.rb:589:in `url_for'
actionpack (3.2.22) lib/action_dispatch/routing/route_set.rb:342:in `url_for'
actionpack (3.2.22) lib/action_dispatch/routing/route_set.rb:216:in `letter_path'
letter_opener_web (1.3.0) app/controllers/letter_opener_web/letters_controller.rb:14:in `show'
actionpack (3.2.22) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
actionpack (3.2.22) lib/abstract_controller/base.rb:167:in `process_action'
actionpack (3.2.22) lib/action_controller/metal/rendering.rb:10:in `process_action'
actionpack (3.2.22) lib/abstract_controller/callbacks.rb:18:in `block in process_action'
activesupport (3.2.22) lib/active_support/callbacks.rb:481:in `block in _run__2034020397138380733__process_action__1798997043620149784__callbacks'
activesupport (3.2.22) lib/active_support/callbacks.rb:215:in `block in _conditional_callback_around_10409'
activesupport (3.2.22) lib/active_support/callbacks.rb:326:in `around'
activesupport (3.2.22) lib/active_support/callbacks.rb:310:in `_callback_around_13'
activesupport (3.2.22) lib/active_support/callbacks.rb:214:in `_conditional_callback_around_10409'
activesupport (3.2.22) lib/active_support/callbacks.rb:403:in `_run__2034020397138380733__process_action__1798997043620149784__callbacks'
activesupport (3.2.22) lib/active_support/callbacks.rb:405:in `__run_callback'
activesupport (3.2.22) lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
activesupport (3.2.22) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (3.2.22) lib/abstract_controller/callbacks.rb:17:in `process_action'
actionpack (3.2.22) lib/action_controller/metal/rescue.rb:29:in `process_action'
actionpack (3.2.22) lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
activesupport (3.2.22) lib/active_support/notifications.rb:123:in `block in instrument'
activesupport (3.2.22) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (3.2.22) lib/active_support/notifications.rb:123:in `instrument'
actionpack (3.2.22) lib/action_controller/metal/instrumentation.rb:29:in `process_action'
actionpack (3.2.22) lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
activerecord (3.2.22) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
newrelic_rpm (3.14.0.305) lib/new_relic/agent/instrumentation/rails3/action_controller.rb:30:in `block in process_action'
newrelic_rpm (3.14.0.305) lib/new_relic/agent/instrumentation/controller_instrumentation.rb:362:in `perform_action_with_newrelic_trace'
newrelic_rpm (3.14.0.305) lib/new_relic/agent/instrumentation/rails3/action_controller.rb:29:in `process_action'
actionpack (3.2.22) lib/abstract_controller/base.rb:121:in `process'
actionpack (3.2.22) lib/abstract_controller/rendering.rb:45:in `process'
rack-mini-profiler (0.9.7) lib/mini_profiler/profiling_methods.rb:106:in `block in profile_method'
actionpack (3.2.22) lib/action_controller/metal.rb:203:in `dispatch'
actionpack (3.2.22) lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
actionpack (3.2.22) lib/action_controller/metal.rb:246:in `block in action'
actionpack (3.2.22) lib/action_dispatch/routing/route_set.rb:73:in `call'
actionpack (3.2.22) lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
actionpack (3.2.22) lib/action_dispatch/routing/route_set.rb:36:in `call'
journey (1.0.4) lib/journey/router.rb:68:in `block in call'
journey (1.0.4) lib/journey/router.rb:56:in `each'
journey (1.0.4) lib/journey/router.rb:56:in `call'
actionpack (3.2.22) lib/action_dispatch/routing/route_set.rb:608:in `call'
railties (3.2.22) lib/rails/engine.rb:484:in `call'
railties (3.2.22) lib/rails/railtie/configurable.rb:30:in `method_missing'
actionpack (3.2.22) lib/action_dispatch/routing/mapper.rb:43:in `call'
journey (1.0.4) lib/journey/router.rb:68:in `block in call'
journey (1.0.4) lib/journey/router.rb:56:in `each'
journey (1.0.4) lib/journey/router.rb:56:in `call'
actionpack (3.2.22) lib/action_dispatch/routing/route_set.rb:608:in `call'
newrelic_rpm (3.14.0.305) lib/new_relic/agent/instrumentation/middleware_tracing.rb:78:in `call'
omniauth (1.2.2) lib/omniauth/strategy.rb:186:in `call!'
omniauth (1.2.2) lib/omniauth/strategy.rb:164:in `call'
newrelic_rpm (3.14.0.305) lib/new_relic/agent/instrumentation/middleware_tracing.rb:78:in `call'
omniauth (1.2.2) lib/omniauth/builder.rb:59:in `call'
newrelic_rpm (3.14.0.305) lib/new_relic/agent/instrumentation/middleware_tracing.rb:78:in `call'
bullet (4.14.7) lib/bullet/rack.rb:12:in `call'
newrelic_rpm (3.14.0.305) lib/new_relic/agent/instrumentation/middleware_tracing.rb:78:in `call'
meta_request (0.3.4) lib/meta_request/middlewares/app_request_handler.rb:13:in `call'
newrelic_rpm (3.14.0.305) lib/new_relic/agent/instrumentation/middleware_tracing.rb:78:in `call'
meta_request (0.3.4) lib/meta_request/middlewares/meta_request_handler.rb:13:in `call'
newrelic_rpm (3.14.0.305) lib/new_relic/agent/instrumentation/middleware_tracing.rb:78:in `call'
newrelic_rpm (3.14.0.305) lib/new_relic/rack/agent_hooks.rb:30:in `traced_call'
newrelic_rpm (3.14.0.305) lib/new_relic/agent/instrumentation/middleware_tracing.rb:78:in `call'
newrelic_rpm (3.14.0.305) lib/new_relic/rack/browser_monitoring.rb:32:in `traced_call'
newrelic_rpm (3.14.0.305) lib/new_relic/agent/instrumentation/middleware_tracing.rb:78:in `call'
railties (3.2.22) lib/rails/rack/log_tailer.rb:17:in `call'
newrelic_rpm (3.14.0.305) lib/new_relic/agent/instrumentation/middleware_tracing.rb:78:in `call'
rack-attack (4.3.0) lib/rack/attack.rb:97:in `call'
newrelic_rpm (3.14.0.305) lib/new_relic/agent/instrumentation/middleware_tracing.rb:78:in `call'
warden (1.1.1) lib/warden/manager.rb:35:in `block in call'
warden (1.1.1) lib/warden/manager.rb:34:in `catch'
warden (1.1.1) lib/warden/manager.rb:34:in `call'
newrelic_rpm (3.14.0.305) lib/new_relic/agent/instrumentation/middleware_tracing.rb:78:in `call'
actionpack (3.2.22) lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
newrelic_rpm (3.14.0.305) lib/new_relic/agent/instrumentation/middleware_tracing.rb:78:in `call'
rack (1.4.7) lib/rack/etag.rb:23:in `call'
newrelic_rpm (3.14.0.305) lib/new_relic/agent/instrumentation/middleware_tracing.rb:78:in `call'
rack (1.4.7) lib/rack/conditionalget.rb:25:in `call'
newrelic_rpm (3.14.0.305) lib/new_relic/agent/instrumentation/middleware_tracing.rb:78:in `call'
actionpack (3.2.22) lib/action_dispatch/middleware/head.rb:14:in `call'
newrelic_rpm (3.14.0.305) lib/new_relic/agent/instrumentation/middleware_tracing.rb:78:in `call'
actionpack (3.2.22) lib/action_dispatch/middleware/params_parser.rb:21:in `call'
newrelic_rpm (3.14.0.305) lib/new_relic/agent/instrumentation/middleware_tracing.rb:78:in `call'
actionpack (3.2.22) lib/action_dispatch/middleware/flash.rb:242:in `call'
newrelic_rpm (3.14.0.305) lib/new_relic/agent/instrumentation/middleware_tracing.rb:78:in `call'
rack (1.4.7) lib/rack/session/abstract/id.rb:210:in `context'
rack (1.4.7) lib/rack/session/abstract/id.rb:205:in `call'
newrelic_rpm (3.14.0.305) lib/new_relic/agent/instrumentation/middleware_tracing.rb:78:in `call'
actionpack (3.2.22) lib/action_dispatch/middleware/cookies.rb:341:in `call'
newrelic_rpm (3.14.0.305) lib/new_relic/agent/instrumentation/middleware_tracing.rb:78:in `call'
activerecord (3.2.22) lib/active_record/query_cache.rb:64:in `call'
newrelic_rpm (3.14.0.305) lib/new_relic/agent/instrumentation/middleware_tracing.rb:78:in `call'
activerecord (3.2.22) lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
newrelic_rpm (3.14.0.305) lib/new_relic/agent/instrumentation/middleware_tracing.rb:78:in `call'
actionpack (3.2.22) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
activesupport (3.2.22) lib/active_support/callbacks.rb:405:in `_run__3710090046209339660__call__4369487391565187203__callbacks'
activesupport (3.2.22) lib/active_support/callbacks.rb:405:in `__run_callback'
activesupport (3.2.22) lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
activesupport (3.2.22) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (3.2.22) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
newrelic_rpm (3.14.0.305) lib/new_relic/agent/instrumentation/middleware_tracing.rb:78:in `call'
rails-dev-tweaks (1.2.0) lib/rails_dev_tweaks/granular_autoload/middleware.rb:36:in `call'
newrelic_rpm (3.14.0.305) lib/new_relic/agent/instrumentation/middleware_tracing.rb:78:in `call'
actionpack (3.2.22) lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
newrelic_rpm (3.14.0.305) lib/new_relic/agent/instrumentation/middleware_tracing.rb:78:in `call'
rack-contrib (1.2.0) lib/rack/contrib/response_headers.rb:17:in `call'
meta_request (0.3.4) lib/meta_request/middlewares/headers.rb:16:in `call'
newrelic_rpm (3.14.0.305) lib/new_relic/agent/instrumentation/middleware_tracing.rb:78:in `call'
actionpack (3.2.22) lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
newrelic_rpm (3.14.0.305) lib/new_relic/agent/instrumentation/middleware_tracing.rb:78:in `call'
actionpack (3.2.22) lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
newrelic_rpm (3.14.0.305) lib/new_relic/agent/instrumentation/middleware_tracing.rb:78:in `call'
/home/thief/.rbenv/versions/1.9.3-p551/gemsets/mfl-32/bundler/gems/browserlog-45c27272346e/lib/browserlog/selective_logger.rb:16:in `call_app'
railties (3.2.22) lib/rails/rack/logger.rb:18:in `call'
quiet_assets (1.1.0) lib/quiet_assets.rb:27:in `call_with_quiet_assets'
newrelic_rpm (3.14.0.305) lib/new_relic/agent/instrumentation/middleware_tracing.rb:78:in `call'
request_store (1.2.0) lib/request_store/middleware.rb:8:in `call'
newrelic_rpm (3.14.0.305) lib/new_relic/agent/instrumentation/middleware_tracing.rb:78:in `call'
actionpack (3.2.22) lib/action_dispatch/middleware/request_id.rb:22:in `call'
newrelic_rpm (3.14.0.305) lib/new_relic/agent/instrumentation/middleware_tracing.rb:78:in `call'
rack (1.4.7) lib/rack/methodoverride.rb:21:in `call'
newrelic_rpm (3.14.0.305) lib/new_relic/agent/instrumentation/middleware_tracing.rb:78:in `call'
rack (1.4.7) lib/rack/runtime.rb:17:in `call'
newrelic_rpm (3.14.0.305) lib/new_relic/agent/instrumentation/middleware_tracing.rb:78:in `call'
activesupport (3.2.22) lib/active_support/cache/strategy/local_cache.rb:72:in `call'
newrelic_rpm (3.14.0.305) lib/new_relic/agent/instrumentation/middleware_tracing.rb:78:in `call'
rack (1.4.7) lib/rack/lock.rb:15:in `call'
newrelic_rpm (3.14.0.305) lib/new_relic/agent/instrumentation/middleware_tracing.rb:78:in `call'
actionpack (3.2.22) lib/action_dispatch/middleware/static.rb:83:in `call'
newrelic_rpm (3.14.0.305) lib/new_relic/agent/instrumentation/middleware_tracing.rb:78:in `call'
rack-mini-profiler (0.9.7) lib/mini_profiler/profiler.rb:276:in `call'
newrelic_rpm (3.14.0.305) lib/new_relic/agent/instrumentation/middleware_tracing.rb:78:in `call'
railties (3.2.22) lib/rails/engine.rb:484:in `call'
railties (3.2.22) lib/rails/application.rb:231:in `call'
railties (3.2.22) lib/rails/railtie/configurable.rb:30:in `method_missing'
newrelic_rpm (3.14.0.305) lib/new_relic/agent/instrumentation/middleware_tracing.rb:78:in `call'
rack (1.4.7) lib/rack/content_length.rb:14:in `call'
railties (3.2.22) lib/rails/rack/log_tailer.rb:17:in `call'
thin (1.6.3) lib/thin/connection.rb:86:in `block in pre_process'
thin (1.6.3) lib/thin/connection.rb:84:in `catch'
thin (1.6.3) lib/thin/connection.rb:84:in `pre_process'
thin (1.6.3) lib/thin/connection.rb:53:in `process'
thin (1.6.3) lib/thin/connection.rb:39:in `receive_data'
eventmachine (1.0.8) lib/eventmachine.rb:1509:in `event_callback'
eventmachine (1.0.8) lib/em/pure_ruby.rb:544:in `block in eventable_read'
eventmachine (1.0.8) lib/em/pure_ruby.rb:542:in `times'
eventmachine (1.0.8) lib/em/pure_ruby.rb:542:in `eventable_read'
/home/thief/.rbenv/versions/1.9.3-p551/lib/ruby/1.9.1/forwardable.rb:201:in `eventable_read'
eventmachine (1.0.8) lib/em/pure_ruby.rb:369:in `block in crank_selectables'
eventmachine (1.0.8) lib/em/pure_ruby.rb:369:in `each'
eventmachine (1.0.8) lib/em/pure_ruby.rb:369:in `crank_selectables'
eventmachine (1.0.8) lib/em/pure_ruby.rb:324:in `block in run'
eventmachine (1.0.8) lib/em/pure_ruby.rb:318:in `loop'
eventmachine (1.0.8) lib/em/pure_ruby.rb:318:in `run'
eventmachine (1.0.8) lib/em/pure_ruby.rb:62:in `run_machine'
eventmachine (1.0.8) lib/eventmachine.rb:193:in `run'
thin (1.6.3) lib/thin/backends/base.rb:73:in `start'
thin (1.6.3) lib/thin/server.rb:162:in `start'
rack (1.4.7) lib/rack/handler/thin.rb:13:in `run'
rack (1.4.7) lib/rack/server.rb:268:in `start'
railties (3.2.22) lib/rails/commands/server.rb:70:in `start'
zeus (0.15.4) lib/zeus/rails.rb:160:in `server'
zeus (0.15.4) lib/zeus.rb:148:in `block in command'
zeus (0.15.4) lib/zeus.rb:135:in `fork'
zeus (0.15.4) lib/zeus.rb:135:in `command'
zeus (0.15.4) lib/zeus.rb:50:in `go'
-e:1:in `<main>'

Request

Parameters:

{"id"=>"1459521465_8b3f119",
 "style"=>"rich"}

Show session dump

Show env dump
Response

Headers:

None
```

**Comment by Blue-Dog-Archolite** [comment]
Turns out this is a namespacing issue.

If mounted inside of a namespace, this error occurs. Outside of namespaces, it works great.

**Comment by pseudomuto** [comment]
This is very old at this point and has no recent activity. I'm going to close it for now. Feel free to open a new issue/PR if this is still a concern.
