### ISSUE TITLE
[Exception] "undefined method `before_filter' for LetterOpenerWeb::LettersController:Class" on Rails5

### ISSUE THREAD

**Issue by kenju** [fgrehm/letter_opener_web#68]
## Environment:

- `ruby: 2.3.1`
- `rails: 5.1.1`

## How to reproduce

1. Instal rails v5.1.x and letter_opneer_web
2. Configure and open the web page

## Stacktrace:

```rb
ActionController::RoutingError - undefined method `before_filter' for LetterOpenerWeb::LettersController:Class
Did you mean?  before_action:
  actionpack (5.1.1) lib/action_dispatch/routing/route_set.rb:45:in `rescue in controller'
  actionpack (5.1.1) lib/action_dispatch/routing/route_set.rb:43:in `controller'
  actionpack (5.1.1) lib/action_dispatch/routing/route_set.rb:29:in `serve'
  actionpack (5.1.1) lib/action_dispatch/journey/router.rb:46:in `block in serve'
  actionpack (5.1.1) lib/action_dispatch/journey/router.rb:33:in `serve'
  actionpack (5.1.1) lib/action_dispatch/routing/route_set.rb:832:in `call'
  railties (5.1.1) lib/rails/engine.rb:522:in `call'
  railties (5.1.1) lib/rails/railtie.rb:185:in `method_missing'
  actionpack (5.1.1) lib/action_dispatch/routing/mapper.rb:17:in `block in <class:Constraints>'
  actionpack (5.1.1) lib/action_dispatch/routing/mapper.rb:46:in `serve'
  actionpack (5.1.1) lib/action_dispatch/journey/router.rb:46:in `block in serve'
  actionpack (5.1.1) lib/action_dispatch/journey/router.rb:33:in `serve'
  actionpack (5.1.1) lib/action_dispatch/routing/route_set.rb:832:in `call'
```

---

I came across this commend. https://github.com/fgrehm/letter_opener_web/issues/46#issuecomment-187751689
May I ask, does this gem not work with Rails 5 yet?

**Comment by kenju** [comment]
We were using `letter_opener_web` with v1.3.0, but this bug was already fixed with v1.3.1.
https://github.com/fgrehm/letter_opener_web/compare/v1.3.0...v1_stable
