### ISSUE TITLE
Does not work with Rails API only

### ISSUE THREAD

**Issue by rawongithub** [fgrehm/letter_opener_web#84]
```
1: from /bundle/gems/letter_opener_web-1.3.3/lib/letter_opener_web/engine.rb:21:in `block in <class:Engine>'
api_1         | /bundle/gems/railties-5.1.5/lib/rails/railtie/configuration.rb:95:in `method_missing': undefined method `assets' for #<Rails::Application::Configuration:0x000056411caebd58> (NoMethodError)
```

**Comment by rawongithub** [comment]
`require 'sprockets/railtie'` in `/config/application.rb` solves the issue

**Comment by wgtgithub** [comment]
Thanks, Rafael
My issue was clearly.
